name: Python application

on: [push, pull_request]

jobs:
  lint_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip virtualenv wheel setuptools
    - name: Lint with pycodestyle
      run: |
        python3 -m pip install flake8
        python3 -m flake8 . --count --ignore=E125,E126,E127,E128,E402,E741,E731,W503,F401,W504 --show-source --statistics --max-line-length=80 --exclude=__pycache__,.tox,.git/,doc/,ceed/player/

  linux_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      env:
        DISPLAY: :99.0
      run: |
        sudo apt update
        sudo apt -y install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev
        sudo apt-get -y install python3-setuptools build-essential libgl1-mesa-dev libgles2-mesa-dev
        python3 -m pip install --upgrade pip virtualenv wheel setuptools
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX
        python3 -m pip install cython https://kivy.org/downloads/ci/linux/kivy/Kivy-2.0.0.dev0-cp37-cp37m-manylinux2010_x86_64.whl trio pillow coveralls docutils PyInstaller https://github.com/matham/cplcom/archive/master.zip
        python3 -m pip install -e . --extra-index-url https://kivy-garden.github.io/simple/
    - name: Test with pytest
      env:
        DISPLAY: :99.0
      run: |
        python3 -m pytest --cov=ceed --cov-report term --cov-branch ceed/tests
    - name: Coveralls upload
      run: python3 -m coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  windows_test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      env:
        KIVY_GL_BACKEND: angle_sdl2
      run: |
        python -m pip install --upgrade pip virtualenv wheel setuptools
        python -m pip install cython kivy_deps.angle kivy_deps.sdl2 kivy_deps.glew https://kivy.org/downloads/ci/win/kivy/Kivy-2.0.0.dev0-cp37-cp37m-win_amd64.whl trio pillow docutils PyInstaller https://github.com/matham/cplcom/archive/master.zip
        python -m pip install -e . --extra-index-url https://kivy-garden.github.io/simple/
    - name: Test with pytest
      env:
        KIVY_GL_BACKEND: angle_sdl2
      run: |
        python -m pytest --cov=ceed --cov-report term --cov-branch ceed/tests

  docs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      env:
          KIVY_DOC_INCLUDE: 1
          KIVY_DOC: 1
      run: |
        python3 -m pip install --upgrade pip virtualenv wheel setuptools
        python3 -m pip install https://kivy.org/downloads/ci/linux/kivy/Kivy-2.0.0.dev0-cp37-cp37m-manylinux2010_x86_64.whl sphinx
        git clone https://github.com/matham/cplcom.git packages
        cd packages
        python3 -m pip install -e .
        cd ..
        python3 -m pip install -e . --extra-index-url https://kivy-garden.github.io/simple/
    - name: Generate docs
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        cd packages/doc
        CPLCOM_CONFIG_DOC_PATH=../../prop_docs.json make html
        cd ../../doc
        CPLCOM_CONFIG_DOC_PATH=../prop_docs.json make html
    - name: gh-pages upload
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cp -r build/html ~/docs_temp

        git config --global credential.helper store
        git config --global user.email "moiein2000@gmail.com"
        git config --global user.name "Matthew Einhorn"

        git checkout --orphan gh-pages
        cp -r .git ~/docs_git
        cd ..
        rm -rf ceed
        mkdir ceed
        cd ceed
        cp -r ~/docs_git .git
        cp -r ~/docs_temp/* .
        echo "" > .nojekyll

        git add .
        git commit -a -m "Docs for git-$GITHUB_SHA"
        git push origin gh-pages -f
