name: Python application

on: [push]

jobs:
  lint_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip virtualenv wheel setuptools --user
    - name: Lint with pycodestyle
      run: |
        python3 -m pip install flake8 --user
        python3 -m flake8 . --count --ignore=E125,E126,E127,E128,E402,E741,E731,W503,F401,W504 --show-source --statistics --max-line-length=80 --exclude=__pycache__,.tox,.git/,doc/,ceed/player/

  linux_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      env:
        DISPLAY: :99.0
      run: |
        sudo apt update
        sudo apt -y install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev
        sudo apt-get -y install python3-setuptools build-essential libgl1-mesa-dev libgles2-mesa-dev
        python3 -m pip install --upgrade pip virtualenv wheel setuptools --user
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX
        python3 -m pip install cython https://kivy.org/downloads/ci/linux/kivy/Kivy-2.0.0.dev0-cp37-cp37m-manylinux2010_x86_64.whl trio pillow coveralls docutils PyInstaller https://github.com/matham/cplcom/archive/master.zip --user
        python3 -m pip install -e . --extra-index-url https://kivy-garden.github.io/simple/ --user
    - name: Test with pytest
      env:
        DISPLAY: :99.0
      run: |
        python3 -m pytest --cov=ceed --cov-report term --cov-branch ceed/tests/test_app/test_app_config.py
    - name: Coveralls upload
      run: python3 -m coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  windows_test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      env:
        KIVY_GL_BACKEND: angle_sdl2
      run: |
        python -m pip install --upgrade pip virtualenv wheel setuptools
        python -m pip install cython kivy_deps.angle kivy_deps.sdl2 kivy_deps.glew https://kivy.org/downloads/ci/win/kivy/Kivy-2.0.0.dev0-cp37-cp37m-win_amd64.whl trio pillow docutils PyInstaller https://github.com/matham/cplcom/archive/master.zip
        python -m pip install -e . --extra-index-url https://kivy-garden.github.io/simple/ --verbose
    - name: Test with pytest
      env:
        KIVY_GL_BACKEND: angle_sdl2
      run: |
        python3 -m pytest --cov=ceed --cov-report term --cov-branch ceed/tests/test_app/test_app_config.py
